---
title: Test jekyll functionality
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: salunkevishal05@gmail.com
description: we will test and understand jekyll working stuff..
baseurl: ''
url: ''
twitter_username: 
github_username: VishalSalunke
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
